apiVersion: v1
kind: ConfigMap
metadata:
  name: config-pipeline
data:
  NAMESPACE: "$(NAMESPACE)"
  DB_TYPE: "PGVECTOR"
  PGVECTOR_COLLECTION_NAME: "rhoai-doc"
  PGVECTOR_URL: "postgresql+psycopg://vectordb:$(DB_PASS)@postgresql-service:5432/vectordb"
  TRANSFORMERS_CACHE: "/cache/.cache"
  SENTENCE_TRANSFORMERS_HOME: "/cache/.cache"
