kind: Secret
apiVersion: v1
metadata:
  name: ds-pipeline-config-llm-rag
  namespace: itay-project
  uid: 10a1f3c1-d975-4f7f-a590-d1ee253f0133
  resourceVersion: "614029723"
  creationTimestamp: "2025-01-06T08:30:51Z"
  managedFields:
    - manager: Mozilla
      operation: Update
      apiVersion: v1
      time: "2025-01-06T12:44:05Z"
      fieldsType: FieldsV1
      fieldsV1:
        "f:data":
          .: {}
          "f:DB_CONF": {}
          "f:EMBED_CONF": {}
          "f:REPO_CONFIG": {}
          "f:S3_CONFIG": {}
          "f:URLS_CONFIG": {}
        "f:type": {}
data:
  DB_CONF: eydEQl9UWVBFJzonUEdWRUNUT1InLCAnUEdWRUNUT1JfQ09MTEVDVElPTl9OQU1FJzoncmhvYWktZG9jJywgJ1BHVkVDVE9SX1VSTCc6ICdwb3N0Z3Jlc3FsK3BzeWNvcGc6Ly92ZWN0b3JkYjpSYWhUZ1BtOTBIc01RNlhacTFCYmNobzMzWXRmVWdMSkh2Sk9jYk9tbDJRVXlDaEMwVERnQXpweTUwcVNIellkQHBvc3RncmVzcWwtc2VydmljZTo1NDMyL3ZlY3RvcmRiJywnUkVESVNfVVJMJzonJywnUkVESVNfSU5ERVgnOicnLCAnUkVESVNfU0NIRU1BJzogJycsICdFTEFTVElDX1VSTCc6JycsICdFTEFTVElDX0lOREVYJzonJywnRUxBU1RJQ19VU0VSJzonJywgJ0VMQVNUSUNfUEFTU1dPUkQnOicnfQ==
  EMBED_CONF: eydUUkFOU0ZPUk1FUlNfQ0FDSEUnOicvY2FjaGUvLmNhY2hlJywnU0VOVEVOQ0VfVFJBTlNGT1JNRVJTX0hPTUUnOicvY2FjaGUvLmNhY2hlJ30=
  REPO_CONFIG: eydSRVBPX1VSTCc6J2h0dHBzOi8vZ2l0aHViLmNvbS9SSEVjb3N5c3RlbUFwcEVuZy9sbG0tb24tb3BlbnNoaWZ0LmdpdCcsJ0RPQ19MT0NBVElPTic6J2V4YW1wbGVzL25vdGVib29rcy9sYW5nY2hhaW4vcmhvZHMtZG9jJ30=
  S3_CONFIG: eydBV1NfQUNDRVNTX0tFWV9JRCc6ICdtaW5pbycsJ0FXU19TRUNSRVRfQUNDRVNTX0tFWSc6ICdtaW5pbzEyMycsJ0FXU19TM19FTkRQT0lOVCc6J2h0dHBzOi8vbWluaW8tYXBpLW1pbmlvLmFwcHMuYWktZGV2MDIua25pLnN5c2VuZy5kZXZjbHVzdGVyLm9wZW5zaGlmdC5jb20nLCdBV1NfUzNfQlVDS0VUJzonZGVtby1sbG0tcmFnJywgJ0FXU19TM19GT0xERVJfUEFUSCc6J3BkZnMnfQ==
  URLS_CONFIG: eydVUkxTX0FSUkFZJzpbImh0dHBzOi8vYWktb24tb3BlbnNoaWZ0LmlvL2dldHRpbmctc3RhcnRlZC9vcGVuc2hpZnQvIiwiaHR0cHM6Ly9haS1vbi1vcGVuc2hpZnQuaW8vZ2V0dGluZy1zdGFydGVkL29wZW5kYXRhaHViLyIsImh0dHBzOi8vYWktb24tb3BlbnNoaWZ0LmlvL2dldHRpbmctc3RhcnRlZC9vcGVuc2hpZnQtYWkvIiwiaHR0cHM6Ly9haS1vbi1vcGVuc2hpZnQuaW8vb2RoLXJob2FpL2NvbmZpZ3VyYXRpb24vIiwiaHR0cHM6Ly9haS1vbi1vcGVuc2hpZnQuaW8vb2RoLXJob2FpL2N1c3RvbS1ub3RlYm9va3MvIiwiaHR0cHM6Ly9haS1vbi1vcGVuc2hpZnQuaW8vb2RoLXJob2FpL252aWRpYS1ncHVzLyIsImh0dHBzOi8vYWktb24tb3BlbnNoaWZ0LmlvL29kaC1yaG9haS9jdXN0b20tcnVudGltZS10cml0b24vIiwiaHR0cHM6Ly9haS1vbi1vcGVuc2hpZnQuaW8vb2RoLXJob2FpL29wZW5zaGlmdC1ncm91cC1tYW5hZ2VtZW50LyIsImh0dHBzOi8vYWktb24tb3BlbnNoaWZ0LmlvL3Rvb2xzLWFuZC1hcHBsaWNhdGlvbnMvbWluaW8vbWluaW8vIl19
type: Opaque
